"""Add layout column to cards

Revision ID: 9bef87d8d83b
Revises: 84fcb0bac772
Create Date: 2026-03-30 00:25:29.837950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bef87d8d83b'
down_revision = '84fcb0bac772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('layout')

    # ### end Alembic commands ###
